export enum CustomOperation {
  EQUAL = "equal",
  NOT_EQUAL = "not_equal",
  GT = "gt",
  GTE = "gte",
  LT = "lt",
  LTE = "lte",
  LIKE = "like",
  STARTS_WITH = "starts_with",
  ENDS_WITH = "ends_with",
  IN = "in",
  NOT_IN = "not_in",
  OPERATION_JOIN_EQUAL = "join_equal",
  OPERATION_JOIN_LIKE = "join_like",
  OPERATION_JOIN_IN = "join_in",
  OPERATION_JOIN_GT = "join_gt",
  OPERATION_JOIN_GTE = "join_gte",
  OPERATION_JOIN_LT = "join_lt",
  OPERATION_JOIN_LTE = "join_lte",
}
